on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/*.kicad_pcb"

name: Render Previews
jobs:
  make-pngs:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        name: [ant, beetle, flea, gnat, midge, mite, mosquito, wasp, yellowjacket]
    name: "Export as PNGs"
    steps:
      # CHECKOUT
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: false

      # PREVIEWS
      - name: Make preview of ${{ matrix.name }}
        uses: ./.github/actions/export-pngs
        with:
          pcb_file: '"./pcbs/${{ matrix.name }}/${{ matrix.name }}.kicad_pcb"'
          pngs_dir: '"./images/${{ matrix.name }}"'

      # # PULL CHANGES
      # - run: git pull

      # # PUBLISH
      # - name: Publish Images
      #   uses: stefanzweifel/git-auto-commit-action@v4.14.1
      #   with:
      #     commit_message: "Update gallery (automated)"
      #     commit_user_name: GitHub Actions Bot

  publish:
    needs: make-pngs
    runs-on: ubuntu-latest
    steps:
      # CHECKOUT
      - name: Checkout
        uses: actions/checkout@v3
        with:
          clean: false
      # UPDATE GALLERY
      - name: Update gallery
        uses: stefanzweifel/git-auto-commit-action@v4.14.1
        with:
          commit_message: "Update gallery (automated)"
          commit_user_name: GitHub Actions Bot
          # file_pattern: "**/*.png"
